name: Weekly Manhwa Scraper

on:
    schedule:
        - cron: "0 0 * * 0"
    workflow_dispatch:

jobs:
    scrape:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install puppeteer axios

            - name: Run scraper
              run: bun index.ts

            - name: Commit and push results
              run: |
                  git config --global user.name "GitHub Action"
                  git config --global user.email "action@github.com"
                  git add manhwa_data.json chapters/ covers/
                  git commit -m "Update manhwa data - $(date)" || echo "No changes to commit"
                  git push
